apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
  namespace: backend
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  backoffLimit: 6
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: backend-sa  
      containers:
        - name: migrate
          image: mohamedessam122002/backend-app:latest
          command: ["python", "manage.py", "migrate"]
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: rds-config
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: rds-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: rds-config
                  key: DB_USER
