# ConfigMap for S3 initialization script
apiVersion: v1
kind: ConfigMap
metadata:
  name: es-s3-init-script
  namespace: monitoring
data:
  init-s3-repo.sh: |
    #!/bin/bash
    set -e
    
    # Wait for Elasticsearch to be ready
    until curl -s http://localhost:9200/_cluster/health | grep -q '"status":"yellow"\|"status":"green"'; do
      echo "Waiting for Elasticsearch..."
      sleep 5
    done
    
    echo "Elasticsearch is ready. Registering S3 repository..."
    
    # Register S3 repository
    curl -X PUT "http://localhost:9200/_snapshot/s3_backup" -H 'Content-Type: application/json' -d '{
      "type": "s3",
      "settings": {
        "bucket": "elasticsearch-logs-backup",
        "region": "eu-north-1",
        "base_path": "snapshots"
      }
    }'
    
    echo ""
    echo "Creating automated snapshot policy..."
    
    # Create automated snapshot policy
    curl -X PUT "http://localhost:9200/_slm/policy/daily-snapshots" -H 'Content-Type: application/json' -d '{
      "schedule": "0 0 * * *",
      "name": "<daily-snap-{now/d}>",
      "repository": "s3_backup",
      "config": {
        "indices": ["*"],
        "ignore_unavailable": false,
        "include_global_state": false
      },
      "retention": {
        "expire_after": "30d",
        "min_count": 5,
        "max_count": 50
      }
    }'
    
    echo ""
    echo "S3 configuration completed!"
---
# Elasticsearch Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      serviceAccountName: elasticsearch-sa
      initContainers:
        - name: init-s3-repo
          image: curlimages/curl:latest
          command: ["/bin/sh", "/scripts/init-s3-repo.sh"]
          volumeMounts:
            - name: init-script
              mountPath: /scripts
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
          env:
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"          
            - name: xpack.security.enabled
              value: "false"
          ports:
            - containerPort: 9200
          resources:                     
            requests:
              memory: "2Gi"                
              cpu: "500m"                     
            limits:
              memory: "2Gi"                  
              cpu: "2"                       
          readinessProbe:
            httpGet:
              path: /_cluster/health?wait_for_status=yellow
              port: 9200
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
      volumes:
        - name: init-script
          configMap:
            name: es-s3-init-script
            defaultMode: 0755
---
# Elasticsearch Service
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: monitoring
spec:
  selector:
    app: elasticsearch
  ports:
    - port: 9200
      targetPort: 9200
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: elasticsearch
#   namespace: monitoring
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: elasticsearch
#   template:
#     metadata:
#       labels:
#         app: elasticsearch
#     spec:
#       containers:
#         - name: elasticsearch
#           image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
#           env:
#             - name: discovery.type
#               value: single-node
#             - name: ES_JAVA_OPTS
#               value: "-Xms512m -Xmx512m"          
#             - name: xpack.security.enabled
#               value: "false"

#           ports:
#             - containerPort: 9200

#           resources:                     
#             requests:
#               memory: "2Gi"                
#               cpu: "500m"                     
#             limits:
#               memory: "2Gi"                  
#               cpu: "2"                       

#           readinessProbe:
#             httpGet:
#               path: /_cluster/health?wait_for_status=yellow
#               port: 9200
#             initialDelaySeconds: 30
#             periodSeconds: 10
#             timeoutSeconds: 5
#             failureThreshold: 10

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: elasticsearch
#   namespace: monitoring
# spec:
#   selector:
#     app: elasticsearch
#   ports:
#     - port: 9200
#       targetPort: 9200
